---
title: "depthdamage"
output: html_document
---

```{r setup, include = FALSE}
## setup
knitr::opts_knit$set(root.dir = 'D:/1-PARRA/')

```

```{r message = FALSE}
## setup information
source('_data/setup.R')

```

```{r}
## get HAZUS damage curves
hazus <- read.csv('_data/depthdamage/HAZUS.csv')
hazus <- hazus %>% 
  filter(Curve != 'San Francisco') %>% 
  mutate(FIA = toNumber(gsub('FIA ', '', Curve))) %>% 
  subset(FIA > 1970) %>% 
  select(-Table, -Curve) %>% 
  pivot_longer(cols = -c('Stories', 'Basement', 'Type', 'FIA'), 
               names_to = 'depth_ft', values_to = 'damage_pct') %>% 
  mutate(depth_ft = depth_ft %>% gsub('\\.', '-', .) %>% 
           gsub('X', '', .) %>% toNumber) %>% 
  mutate(depth_m = depth_ft/mft,
         damage_pct = damage_pct/100,
         class = paste(Stories, Basement, Type))

ggplot(hazus) + 
  geom_line(aes(x = depth_m, y = damage_pct, group = class, 
                color = factor(Stories), linetype = Type, alpha = Basement), size = 1) + 
  scale_linetype_manual(values = c(2,1)) + 
  scale_alpha_manual(values = c(0.25, 1)) + 
  scale_y_origin(labels = percent)

ggplot(hazus %>% filter(Basement == 'Y') %>% 
         mutate(depth_m = depth_m + 
                  case_when(Type == 'Struct' ~ 3/mft, Type == 'Cont' ~ 4/mft))) + 
  geom_line(aes(x = depth_m, y = damage_pct, group = class,
            color = factor(Stories), linetype = Type), size = 1) + 
  scale_linetype_manual(values = c(2,1)) + 
  scale_y_origin(labels = percent)

```

```{r}
## get FLEMO damage curves
flemo <- read.csv('_data/depthdamage/FLEMO.csv')
flemo <- flemo %>% 
  mutate(depth_m = cm/100) %>% 
  select(-cm, -ft) %>% 
  pivot_longer(cols = -depth_m, names_to = 'class', values_to = 'damage_pct') %>% 
  filter(grepl(pattern = 'SFH', x = class)) %>% 
  mutate(damage_pct = damage_pct/100)

ggplot(flemo) + 
  geom_line(aes(x = depth_m, y = damage_pct, group = class, color = class), size = 1) + 
  scale_y_origin(labels = percent)

```

```{r}
## get beta distribution parameters
wing2020 <- data.frame(
  depth_ft = c(1:5,7), 
  alpha = c(0.42, 0.48, 0.49, 0.53, 0.68, 0.80),
  beta = c(0.80, 0.65, 0.52, 0.41, 0.42, 0.38)) %>% 
  mutate(mu = alpha/(alpha+beta)) %>% 
  mutate(depth_m = depth_ft/mft)

dx <- 0.01
map_dfc(.x = 1:nrow(wing2020), 
  .f = ~dbeta(x = seq(dx, 1-dx, dx), shape1 = wing2020$alpha[.x], 
              shape2 = wing2020$beta[.x])) %>%
  setNames(wing2020$depth_ft) %>% 
  mutate(damage_pct = seq(dx, 1-dx, dx)) %>% 
  pivot_longer(cols = -damage_pct, names_to = 'depth_ft', values_to = 'damage_prob') %>% 
  mutate(depth_ft = toNumber(depth_ft)) %>% 
  ggplot() + 
  ggridges::geom_density_ridges(
    aes(x = damage_pct, y = depth_ft, group = depth_ft, height = damage_prob), stat = 'identity') + 
  scale_x_continuous(labels = percent) + 
  scale_y_origin()

```

```{r}
## explore extrapolation for beta parameters

ggplot() + 
  geom_line(aes(x = 0:10, y = predict(
    lm(alpha ~ depth_m, data = wing2020), newdata = data.frame(depth_m = 0:10))),
    color = 'grey50') + 
  geom_point(data = wing2020, aes(x = depth_m, y = alpha)) + 
  scale_x_origin('Water Depth (m)') + scale_y_origin('alpha')

ggplot() + 
  geom_line(aes(x = (0:100)/10, y = 1/predict(
    lm(1/beta ~ depth_m, data = wing2020), newdata = data.frame(depth_m = (0:100)/10))),
    color = 'grey50') + 
  geom_point(data = wing2020, aes(x = depth_m, y = beta)) + 
  scale_x_origin('Water Depth (m)') + scale_y_origin('beta')

data.frame(depth_m = (0:100)/10) %>% 
  mutate(alpha = predict(lm(alpha ~ depth_m, data = wing2020), 
                         newdata = data.frame(depth_m))) %>% 
  mutate(beta = 1/predict(lm(1/beta ~ depth_m, data = wing2020), 
                          newdata = data.frame(depth_m))) %>% 
  mutate(mu = alpha/(alpha+beta))

```


```{r}
## save out
save(hazus, flemo, wing2020, file = '_data/depthdamage/depthdamage.Rdata')

```

