---
title: "Untitled"
output: html_document
---


```{r}
inun <- inundation[[1]]
dm <- damage[[1]][,-(ncol(damage[[1]])-0:2)]
dm <- dm[inun[]>0]
inun <- inun[inun[]>0]
ggplot() + geom_point(aes(x = inun, y = dm), alpha = 0.05)

find_nearest <- function(x, vector) map_dbl(.x = x, .f = ~which.min(abs(.x-vector)))
beta <- data.frame(depth_m = (0:100)/10) %>% 
  mutate(alpha = predict(
    lm(alpha ~ depth_m, data = wing2020), newdata = data.frame(depth_m))) %>% 
  mutate(beta = 1/predict(
    lm(1/beta ~ depth_m, data = wing2020), newdata = data.frame(depth_m))) %>% 
  mutate(mu = alpha/(alpha+beta))
dm.beta <- map2_dbl(
  .x = beta$alpha[find_nearest(inun, beta$depth_m)],
  .y = beta$beta[find_nearest(inun, beta$depth_m)],
  .f = ~rbeta(1, shape1 = .x, shape2 = .y))
ggplot() + geom_point(aes(x = inun, y = dm.beta), alpha = 0.05)

find_nearest(inun, beta$depth_m) %>% table %>% as.data.frame %>% plot

```

```{r}
## calculate the number of buildings inundated by each simulation
buildings.coord <- st_coordinates(buildings)
num_cores <- 5
cl <- parallel::makeCluster(num_cores)
registerDoSNOW(cl)
pb <- txtProgressBar(min = 0, max = 1001, style = 3)
inundated <- 
  foreach (file = list.files('_sensitivity/surrogate/sherlock_grid/results/'),
    .packages = c('raster', 'terra', 'dplyr'), 
    .combine = 'rbind', .inorder = FALSE,
    .options.snow = list(progress = function(n) setTxtProgressBar(pb, n))) %dopar% {
    i <- file %>% gsub('gridded', '', .) %>% gsub('.max', '', .) %>% toNumber
    inun <- rast(paste0('_sensitivity/surrogate/sherlock_grid/results/', file)) %>% 
      terra::extract(buildings.coord)
    c(sim = i, inundated = sum(inun>0))
    }
stopCluster(cl)

## join to samples
samples %>% 
  left_join(data.frame(inundated), by = 'sim') %>% 
  ggplot() + 
  geom_point(aes(x = Qp, y = tp, color = inundated>2197)) + 
  # scale_color_scico(palette = 'lajolla') + 
  geom_hline(yintercept = casestudy$tp_hrs, linetype = 'dashed') + 
  geom_vline(xintercept = casestudy$Qp_m3s, linetype = 'dashed') + 
  scale_x_origin() + scale_y_origin() 
samples %>% 
  left_join(data.frame(inundated), by = 'sim') %>% 
  ggplot() + 
  geom_point(aes(x = Qp, y = tp, color = inundated>1600)) + 
  # scale_color_scico(palette = 'lajolla') + 
  geom_hline(yintercept = casestudy$tp_hrs, linetype = 'dashed') + 
  geom_vline(xintercept = casestudy$Qp_m3s, linetype = 'dashed') + 
  scale_x_origin() + scale_y_origin() 
samples %>% 
  left_join(data.frame(inundated), by = 'sim') %>% 
  ggplot() + 
  geom_point(aes(x = Qp, y = tp, color = inundated>1200)) + 
  # scale_color_scico(palette = 'lajolla') + 
  geom_hline(yintercept = casestudy$tp_hrs, linetype = 'dashed') + 
  geom_vline(xintercept = casestudy$Qp_m3s, linetype = 'dashed') + 
  scale_x_origin() + scale_y_origin() 

```

```{r}
## why did mitigated come out as having zero loss? 

## define area of interest (aoi)
load('_data/aoi/aoi.Rdata')

## load foundation information
load('_data/foundations/foundations.Rdata')

## load depth-damage information
load('_data/depthdamage/depthdamage.Rdata')
hazus <- hazus %>%
  filter(Basement == 'Y') %>%
  mutate(depth_m = depth_m + 3/mft) %>%
  group_by(depth_m) %>%
  summarize(damage_min = Min(damage_pct),
            damage_mean = Mean(damage_pct),
            damage_max = Max(damage_pct))
flemo <- flemo %>% group_by(depth_m) %>%
  summarize(damage_min = Min(damage_pct), 
            damage_mean = Mean(damage_pct), 
            damage_max = Max(damage_pct))

## load building information
load('_data/buildings/buildings.Rdata')

## determine mitigated elevations
rp100 <- raster('_sensitivity/rp100/sherlock_bestfit/results/bestfit.max', crs = projection(aoi))
buildings$raised_m <- unlist(unname(terra::extract(rast(rp100), st_coordinates(buildings))))

## load inundation
load('_results/_troubleshooting/INUN.Rdata')

```

```{r}
load('_data/catalog/catalog.Rdata')

## create AR dataframe to run below
AR <- catalog %>%
  transmute(n.AR = 1:nrow(.), IVT_max, duration, sm)

## calculate n.AR
n.AR <- max(AR$n.AR)

## fit quantile regression model
fun <- precip ~ IVT_max*duration
temp <-
  foreach (t = seq(0, 1, 0.01), .combine = 'rbind') %do% {
    model <- rq(fun, data = catalog %>% rename(precip = precip_mm), tau = t)
    prediction <- predict(model)
    prediction <- ifelse(prediction < 0, 0, prediction)
    c(tau = t, RMSE = RMSE(sort(prediction), sort(catalog$precip_mm)))
  }
tau.best <- temp %>% as.data.frame %>% .[which.min(.$RMSE), 'tau']
model <- rq(fun, data = catalog %>% rename(precip = precip_mm), tau = tau.best)
AR <- AR %>%
  mutate(precip.mean = predict.rq(model, AR),
         precip.sd = predict.se(model, catalog %>% rename(precip = precip_mm), AR))

## add back observed information
catalog %>% 
  mutate(AR = 1:nrow(.)) %>% 
  transmute(AR, IVT_max, duration, precip_obs = precip_mm) %>% 
  left_join(AR %>% transmute(AR = n.AR, precip_sim_mean = precip.mean, 
                             precip_sim_sd = precip.sd), by = 'AR') %>% 
  write.table('C:/Users/cbowers/Desktop/catalog.csv', row.names = FALSE, sep = ',')

temp <- catalog %>% 
  mutate(AR = 1:nrow(.)) %>% 
  transmute(AR, IVT_max, duration, precip_obs = precip_mm) %>% 
  left_join(AR %>% transmute(AR = n.AR, precip_sim_mean = precip.mean, 
                             precip_sim_sd = precip.sd), by = 'AR')

ggplot(temp) + 
  geom_point(aes(x = precip_obs, y = precip_sim_mean-precip_obs))

```

