---
title: "Untitled"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_knit$set(root.dir = 'D:/1-PARRA/')
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
knitr::opts_chunk$set(results = 'hold', fig.show = 'hold', fig.align = 'center')
rm(list=ls())

```

```{r}
## setup information
source('_data/setup.R')
source('_data/plots.R')

## set parallel backend
num_cores <- 5

## load catalog
load('_data/catalog/catalog.Rdata')

# ## load location information
# load('_data/lisflood/dem.Rdata')
# load('_data/aoi/aoi.Rdata')
# load('_data/depthdamage/depthdamage.Rdata')
# 
# ## load required packages
# require(dataRetrieval)

## define colors 
roma.colors <- scico(n = 5, palette = 'roma')

## set random seed for reproducibility
set.seed(7395)

```

goal of this script: update the precipitation model

```{r}
# ## fit quantile regression model
# fun <- precip ~ IVT_max*duration
# temp <-
#   foreach (t = seq(0, 1, 0.01), .combine = 'rbind') %do% {
#     model <- rq(fun, data = catalog %>% rename(precip = precip_mm), tau = t)
#     prediction <- predict(model)
#     prediction <- ifelse(prediction < 0, 0, prediction)
#     c(tau = t, RMSE = RMSE(sort(prediction), sort(catalog$precip_mm)))
#   }
# tau.best <- temp %>% as.data.frame %>% .[which.min(.$RMSE), 'tau']
# model <- rq(fun, data = catalog %>% rename(precip = precip_mm), tau = 0.63)
# AR <- AR %>%
#   mutate(precip.mean = predict.rq(model, AR),
#          precip.sd = predict.se(model, catalog %>% rename(precip = precip_mm), AR))

```

```{r}
## fit OLS regression model 
fun <- precip_mm ~ IVT_max*duration
model.ols <- lm(fun, data = catalog)
# summary(model.ols)
prediction.ols <- predict(model.ols)

```

```{r}
## plot predictors vs. OLS residuals
ggplot(catalog) +
  geom_hline(yintercept = 0, color = 'grey70') +
  geom_hline(yintercept = c(1,-1)*sd(model.ols$residuals),
             color = 'grey70', linetype = 'dashed') +
  geom_vline(aes(xintercept = quantile(IVT_max, 0.5), color = '50')) + 
  geom_vline(aes(xintercept = quantile(IVT_max, 0.75), color = '75')) + 
  geom_vline(aes(xintercept = quantile(IVT_max, 0.9), color = '90')) + 
  geom_point(aes(x = IVT_max, y = precip_mm - prediction.ols)) +
  scale_color_manual(values = roma.colors) + 
  scale_x_continuous(limits = c(250,NA), expand = expansion(mult = c(0, 0.01)))
ggplot(catalog) +
  geom_hline(yintercept = 0, color = 'grey70') +
  geom_hline(yintercept = c(1,-1)*sd(model.ols$residuals),
             color = 'grey70', linetype = 'dashed') +
  geom_vline(aes(xintercept = quantile(duration, 0.5), color = '50')) + 
  geom_vline(aes(xintercept = quantile(duration, 0.75), color = '75')) + 
  geom_vline(aes(xintercept = quantile(duration, 0.9), color = '90')) + 
  geom_point(aes(x = duration, y = precip_mm - prediction.ols)) +
  scale_color_manual(values = roma.colors) + 
  scale_x_origin()

```

```{r}
## calculate WLS + robust standard errors
catalog <- catalog %>% 
  mutate(precip.star = precip_mm / sqrt(IVT_max*duration),
        c.star = 1 / sqrt(IVT_max*duration),
        IVT.star = IVT_max / sqrt(IVT_max*duration),
        dur.star = duration / sqrt(IVT_max*duration),
        interact.star = sqrt(IVT_max*duration))
model.hetskd <- lm(precip.star ~ c.star + IVT.star + dur.star + interact.star + 0, data = catalog) 
se.hetskd <- summary(model.hetskd)$sigma

model.wls <- lm(precip_mm ~ IVT_max*duration, data = catalog, weights = 1/(IVT_max*duration))

```

```{r}
## plot expectation of OLS vs. WLS
catalog <- catalog %>% 
  mutate(precip.ols = predict(model.ols), 
         precip.wls = predict(model.wls),
         precip.hetskd = predict(model.hetskd)*sqrt(catalog$IVT_max*catalog$duration))
ggplot(catalog) + 
  geom_point(aes(x = precip.ols, y = precip.wls)) + 
  scale_x_origin('OLS Prediction') + scale_y_origin('WLS Prediction') + 
  geom_parity() + coord_fixed() + 
  theme_classic()

```

```{r}
## plot Gaussian vs. robust standard errors
error.ols <- rnorm(nrow(catalog), sd = summary(model.ols)$sigma)
error.hetskd <- rnorm(nrow(catalog), sd = se.hetskd) * sqrt(catalog$IVT_max*catalog$duration)

ggplot(catalog) + 
  geom_vline(xintercept = 0, color = 'grey70') + 
  geom_density(aes(x = precip_mm - predict(model.ols), color = 'OLS Residuals'), size = 1) + 
  geom_density(aes(x = error.ols, color = 'Gaussian Standard Errors'), size = 1) +
  geom_density(aes(x = error.hetskd, color = 'Robust Standard Errors'), size = 1) + 
  scale_color_manual('', values = baker[c(2,1,3)], 
    breaks = c('OLS Residuals', 'Gaussian Standard Errors', 'Robust Standard Errors')) + 
  scale_x_continuous('Precipitation Residuals', 
    breaks = seq(-200, 200, 50), limits = c(-175,175)) + 
  scale_y_origin('Probability Density') + 
  theme_classic() + theme(legend.position = c(0.8,0.8))
ggplot(catalog, aes(y = (1:nrow(catalog))/(nrow(catalog)+1))) + 
  geom_step(aes(x = sort(precip_mm - predict(model.ols)), color = 'OLS Residuals'), size = 1) + 
  geom_step(aes(x = sort(error.ols), color = 'Gaussian Standard Errors'), size = 1) +
  geom_step(aes(x = sort(error.hetskd), color = 'Robust Standard Errors'), size = 1) + 
  scale_color_manual('', values = baker[c(2,1,3)], 
    breaks = c('OLS Residuals', 'Gaussian Standard Errors', 'Robust Standard Errors')) + 
  scale_x_continuous('Precipitation Residuals', 
    breaks = seq(-200, 200, 50), limits = c(-175,175)) + 
  scale_y_origin('Probability of Exceedance') + 
  theme_classic() + theme(legend.position = c(0.8,0.4))

ggplot(catalog) + 
  geom_vline(xintercept = 0, color = 'grey70') + 
  geom_density(aes(x = precip_mm - predict(model.wls), color = 'WLS Residuals'), size = 1) + 
  geom_density(aes(x = error.ols, color = 'Gaussian Standard Errors'), size = 1) +
  geom_density(aes(x = error.hetskd, color = 'Robust Standard Errors'), size = 1) + 
  scale_color_manual('', values = baker[c(2,1,3)], 
    breaks = c('WLS Residuals', 'Gaussian Standard Errors', 'Robust Standard Errors')) + 
  scale_x_continuous('Precipitation Residuals', 
    breaks = seq(-200, 200, 50), limits = c(-175,175)) + 
  scale_y_origin('Probability Density') + 
  theme_classic() + theme(legend.position = c(0.8,0.8))
ggplot(catalog, aes(y = (1:nrow(catalog))/(nrow(catalog)+1))) + 
  geom_step(aes(x = sort(precip_mm - predict(model.wls)), color = 'WLS Residuals'), size = 1) + 
  geom_step(aes(x = sort(error.ols), color = 'Gaussian Standard Errors'), size = 1) +
  geom_step(aes(x = sort(error.hetskd), color = 'Robust Standard Errors'), size = 1) + 
  scale_color_manual('', values = baker[c(2,1,3)], 
    breaks = c('WLS Residuals', 'Gaussian Standard Errors', 'Robust Standard Errors')) + 
  scale_x_continuous('Precipitation Residuals', 
    breaks = seq(-200, 200, 50), limits = c(-175,175)) + 
  scale_y_origin('Probability of Exceedance') + 
  theme_classic() + theme(legend.position = c(0.8,0.4))

```

```{r}
## fit a distribution to the top 10% of OLS residuals
# temp <- 
#   foreach (i = seq(0, 1, 0.01), .combine = 'c') %do% {
#     catalog %>% 
#       filter(duration >= quantile(duration, i) & IVT_max >= quantile(IVT_max, i)) %>% 
#       nrow
#   }
# seq(0, 1, 0.01)[temp<=0.1*nrow(catalog)][1]
extreme.id <- catalog %>% 
  mutate(n.AR = 1:nrow(.)) %>% 
  filter(duration >= quantile(duration, 0.81) & IVT_max >= quantile(IVT_max, 0.81)) %>% 
  pull(n.AR)
extreme.resid <- model.ols$residuals[extreme.id]

ggplot() + 
  geom_histogram(aes(x = extreme.resid), bins = sqrt(length(extreme.resid)),
                 color = 'black', fill = 'grey90') + 
  geom_vline(xintercept = 0, color = 'grey50') +
  geom_vline(xintercept = c(1,-1)*sd(extreme.resid),
             color = 'grey50', linetype = 'dashed') +
  geom_vline(xintercept = c(3,-3)*sd(extreme.resid),
             color = 'grey50', linetype = 'dotted') +
  scale_y_origin()
mean(extreme.resid)
sd(extreme.resid)

```

```{r}
## define mixture model for error distribution
error.hetskd <- rnorm(100, sd = se.hetskd) * sqrt(catalog$IVT_max[1]*catalog$duration[1])
error.extreme <- rnorm(100, sd = sd(extreme.resid))

error.mix <- 
  cbind(error.hetskd, error.extreme) %>% 
  as.data.frame %>% 
  mutate(id = sample(c(0,1), size = 100, replace = TRUE, prob = c(0.9, 0.1))) %>% 
  mutate(error.mix = case_when(id==0 ~ error.hetskd, id==1 ~ error.extreme)) %>% 
  pull(error.mix)

hist(error.hetskd)

```

```{r}
## plot multiple Q-Q realizations
for (i in 1:10) {
  precip.qq <-
    generate_precip(
      AR = catalog %>% transmute(n.AR = 1:nrow(.), IVT_max, duration, sm),
      catalog = catalog,
      probabilistic = TRUE, n.precip = 1) %>%
    rename(precip_sim = precip_mm) %>%
    left_join(catalog %>% transmute(n.AR = 1:nrow(.), precip_obs = precip_mm),
              by = 'n.AR')
  precip.max <- max(c(max(precip.qq$precip_sim), max(precip.qq$precip_obs)))
  ggplot(precip.qq) +
    geom_point(aes(x = sort(precip_obs), y = sort(precip_sim)), size = 0.75) +
    coord_cartesian(xlim = c(NA, precip.max), ylim = c(NA, precip.max)) +
    scale_x_origin('Observed Precipitation Quantile (mm)') +
    scale_y_origin('Simulated Precipitation Quantile (mm)') +
    geom_parity() + coord_fixed()
  ggsave(paste0('C:/Users/cbowers/Desktop/residuals', i, '.png'), height = 3)
}

```

