---
title: "foundations"
output: html_document
---

This script creates the dataframe $nsi1.found$, which summarizes aggregate foundation characteristics by census tract in Sonoma County.

Corinne Bowers 

7/28/21

```{r setup, include = FALSE}
## setup
knitr::opts_knit$set(root.dir = 'D:/1-PARRA/')

```

```{r message = FALSE}
## setup information
source('_data/setup.R')
source('_data/plots.R')

```

```{r}
## load NSI data
nsi1 <- read.csv('_data/foundations/nsi1.csv') %>% 
  st_as_sf(coords = c('X', 'Y'), crs = 4269) %>% 
  st_transform(6417)

## summarize NSI foundation info by census tract
nsi1 <- nsi1 %>% 
  st_intersection(sonoma) %>% 
  st_drop_geometry 

## calculate foundations by original method
nsi1.found <- nsi1 %>% 
  mutate(GEOID = toNumber(GEOID)) %>% 
  mutate(counter = 1) %>% 
  group_by(GEOID, Found_Ht, Found_Type) %>% 
  summarize(n = sum(counter), .groups = 'drop') %>% 
  mutate(foundation = paste(Found_Type, Found_Ht, sep = '_')) %>% 
  pivot_wider(id_cols = 'GEOID', names_from = 'foundation', values_from = 'n') %>% 
  dplyr::select(-`SolidWall_7`)
nsi1.found[is.na(nsi1.found)] <- 0
nsi1.found[,-1] <- nsi1.found[,-1] / apply(nsi1.found[,-1], 1, sum)

## calculate foundations by new method
nsi1.edited <- nsi1 %>% 
  mutate(GEOID = toNumber(GEOID)) %>% 
  mutate(counter = 1) %>% 
  group_by(GEOID, Found_Type) %>% 
  summarize(n = sum(counter), .groups = 'drop') %>% 
  pivot_wider(id_cols = 'GEOID', names_from = 'Found_Type', values_from = 'n') %>% 
  select(-SolidWall)
nsi1.edited[is.na(nsi1.edited)] <- 0
nsi1.edited[,-1] <- nsi1.edited[,-1] / apply(nsi1.edited[,-1], 1, sum)
  
## calculate with no foundations
nsi1.base <- data.frame(GEOID = nsi1.found$GEOID, 'All_0' = 1)

```

```{r}
## save out
save(nsi1.found, nsi1.edited, nsi1.base, file = '_data/foundations/foundations.Rdata')

```

