---
title: "NFHL"
output: html_document
---

This script creates $NFHL.Rdata$, which contains obs (the raster file of NFHL floodplain pixels) and obs.full (the raster file of only the NFHL floodplain pixels associated with the Russian River).

```{r setup, include = FALSE}
## setup
knitr::opts_knit$set(root.dir = 'D:/1-PARRA/_data/')

```

```{r message = FALSE}
## setup information
source('setup.R')

## load necessary files
load('aoi/aoi.Rdata')
load('lisflood/dem.Rdata')

```

```{r NFHL}
#### define NFHL data as the "observed" case ####

## load NFHL data from file
# https://catalog.data.gov/dataset/national-flood-hazard-layer-nfhl
NFHL <- st_read('NFHL/NFHL_06_20190810.gdb', layer = 'S_Fld_Haz_Ar', quiet = TRUE) %>% 
  st_transform(6417)
  
## extract floodzone polygons
floodzone <- function(x) {
  if (x %in% c('A', 'A99', 'AE', 'AH', 'AO')) { return('YES')
  } else if (x %in% c('V', 'VE')) { return('WAVE')
  } else if (x %in% c('D', 'X')) { return('NO')
  } else if (x == 'OPEN WATER') { return('WATER')
  } else return(NA)
}
NFHL <- NFHL %>%
  mutate(FLOODPLAIN = factor(apply(data.frame(NFHL$FLD_ZONE), 1, function(x) floodzone(x)))) %>%
  select(FLOODPLAIN) %>%
  subset(FLOODPLAIN == 'YES') %>%
  transmute(NFHL = 1)

```

```{r obs.full}
#### create raster file that matches resolution of the DEM ####

obs.full <- NFHL %>%
  st_cast('POLYGON') %>%
  st_crop(aoi) %>%
  as('Spatial') %>%
  rasterize(dem, getCover = TRUE)
obs.full <- obs.full > 0.5

```

```{r obs}
#### get rid of floodplain pixels not associated with the Russian River ####

## load additional rivers and creeks in Sonoma County
# https://data.ca.gov/dataset/national-hydrography-dataset-nhd
remove.pixels <- st_read('NHD/MajorRiversAndCreeks.shp', quiet = TRUE) %>% st_zm %>%
  st_transform(6417) %>%
  st_crop(sonoma) %>%
  filter(GNIS_Name %in% c('Dry Creek', 'Mark West Creek', 'Austin Creek')) %>%
  filter(!(OBJECTID %in% c(1294, 1297, 1298, 42552, 106984, 1263, 1264,
                           106986, 20379, 57388, 1653, 1652, 116351))) %>%
  st_union %>%
  st_buffer(dist = 250) %>%
  st_difference(russian %>% st_transform(6417) %>% st_buffer(500) %>% st_union) %>%
  as('Spatial') %>%
  rasterize(dem)

## remove non-Russian River pixels 
obs <- obs.full %>% overlay(remove.pixels, fun = function(x, y) ifelse(is.na(y), x, 0))

```

```{r plot}
## plot removed cells
ggplot() + 
  geom_sf(data = sonoma %>% st_crop(aoi), color = 'grey70', fill = 'grey90') + 
  geom_raster(data = raster.df(remove.pixels) %>% filter(!is.na(value)),
              aes(x=x, y=y), fill = 'red') + 
  geom_raster(data = raster.df(obs.full) %>% filter(value>0), 
              aes(x=x, y=y), fill = 'grey50') + 
  geom_sf(data = russian %>% st_transform(6417) %>% st_crop(aoi), size = 1) + 
  geom_sf(data = aoi, fill = NA) + 
  theme_void()

```


```{r save}
## save out values
save(NFHL, obs, obs.full, remove.pixels, file = 'NFHL/NFHL.Rdata')

```
