---
title: "nonzero"
output: html_document
---

This script creates three files:

* $nonzero$ is the raster grid of cells that flooded in at least one of the 5,000 surrogate model runs.
* $nonzero.buffer$ is the $nonzero$ raster plus a conservative buffer of 100 meters.
* $points$ is the vector list of cell IDs for $nonzero.buffer$.

Corinne Bowers

7/2/21

```{r setup, include = FALSE}
## setup
knitr::opts_knit$set(root.dir = 'D:/1-PARRA/_data/')

```

```{r message = FALSE}
## setup information
source('setup.R')

## load necessary files
load('aoi/aoi.Rdata')
load('lisflood/dem.Rdata')
load('samples/samples.Rdata')

```

```{r nonzero}
## find nonzero cells (cells that flooded in at least one simulation)
start <- Sys.time()
# pb <- txtProgressBar(min = 0, max = 5000, style = 3)
cl <- parallel::makeCluster(round(detectCores()*2/3))
registerDoSNOW(cl)
nonzero <-
  foreach (i = 1:5001, .combine = '+', 
    # .options.snow = list(progress = function(n) setTxtProgressBar(pb, n)),
    .packages = 'raster', .inorder = FALSE) %dopar% {
      if (i %in% good) {
        file <- paste0('samples/results/gridded', i, '.max')
        raster(file) > 0
      } else {
        dem*0
      }
    }
stopCluster(cl)
Sys.time() - start

```

```{r buffer}
## get rid of Pacific Ocean cells
crs(nonzero) <- crs(dem)
nonzero <- nonzero %>% 
  overlay(dem, fun = function(x, y) ifelse(y<=1, NA, x))

## buffer nonzero cells to create a conservative boundary
nonzero.buffer <- nonzero %>%
  raster.df %>%
  filter(!is.na(value) & value > 0) %>%
  mutate(value = 1) %>%
  rasterFromXYZ %>%
  rasterToPolygons %>%
  st_as_sf %>%
  st_union %>%
  st_set_crs(6417) %>%
  st_cast(to = 'POLYGON') %>%
  lapply(function(x) x[1]) %>%
  st_multipolygon %>%
  st_buffer(100) %>% #meters
  as('Spatial') %>%
  rasterize(dem) %>% 
  overlay(dem, fun = function(x, y) ifelse(y<=1, NA, x))

## extract ids for nonzero cells
points <- which(!is.na(nonzero.buffer[]))

```

```{r include = FALSE}
## gut-check plot
ggplot() + 
  geom_raster(data = raster.df(nonzero.buffer) %>% filter(!is.na(value)), 
              aes(x=x, y=y, fill='buffer')) + 
  geom_raster(data = raster.df(nonzero) %>% filter(!is.na(value)) %>% filter(value>0), 
              aes(x=x, y=y, fill='nonzero')) + 
  scale_fill_discrete(na.value = NA) + 
  coord_sf(crs = crs(dem))

```

```{r}
## save out 
save(nonzero, nonzero.buffer, points, file = 'nonzero/nonzero.Rdata')

```

